# Generated by Django 3.1.1 on 2020-09-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(default=1, unique=True)),
                ('title', models.CharField(default='title', help_text='Напишите название истории!', max_length=300)),
                ('titleId', models.IntegerField(default=1, unique=True)),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
