# Generated by Django 3.1.1 on 2020-09-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='pub_time',
        ),
    ]
