# Generated by Django 3.1.1 on 2020-09-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0003_auto_20200929_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
