# Generated by Django 3.1.1 on 2020-09-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0004_stories_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='text',
            field=models.CharField(default='TEXT', max_length=300),
        ),
    ]
