# Generated by Django 3.1.1 on 2020-09-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0005_stories_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'Историю', 'verbose_name_plural': 'Истории'},
        ),
    ]
