# Generated by Django 3.1.1 on 2020-09-29 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0006_auto_20200929_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 8, 1, 41, 760372, tzinfo=utc)),
        ),
    ]
