# Generated by Django 3.1.1 on 2020-09-29 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0007_auto_20200929_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
