# Generated by Django 3.1.1 on 2020-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0009_auto_20200929_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
