# Generated by Django 3.1.1 on 2020-10-06 08:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0010_auto_20200929_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='paintforcar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameofpaint', models.IntegerField(default='', help_text='Введите наименование краски')),
                ('vendor_code', models.CharField(default='', help_text='Введите артикул краски', max_length=300)),
                ('colour', models.CharField(default='', help_text='Введите цвет краски', max_length=300)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='Описание краски', max_length=300)),
            ],
            options={
                'verbose_name': 'Краска',
                'verbose_name_plural': 'Краски',
            },
            managers=[
                ('allcolours', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stories',
            managers=[
                ('storytitles', django.db.models.manager.Manager()),
            ],
        ),
    ]
