# Generated by Django 3.1.1 on 2020-10-06 11:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0011_auto_20201006_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_product', models.CharField(default='', help_text='Введите название категории', max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
            managers=[
                ('allcategories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='mobile_phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_name', models.CharField(help_text='Введите наименование мобильного телефона', max_length=300, unique=True)),
                ('descriprion', models.TextField()),
                ('specification', models.CharField(choices=[('display', ((5, 'inch'), (5, 'cm'))), ('resolution', (('1280x720', 'HD'), ('1920,1080', 'fullHD')))], default=(('display', ((5, 'inch'), (5, 'cm'))), ('resolution', (('1280x720', 'HD'), ('1920,1080', 'fullHD')))), max_length=300)),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.AlterModelOptions(
            name='paintforcar',
            options={'verbose_name': 'Краску', 'verbose_name_plural': 'Краски'},
        ),
        migrations.AlterField(
            model_name='paintforcar',
            name='nameofpaint',
            field=models.CharField(default='', help_text='Введите наименование краски', max_length=300),
        ),
    ]
