# Generated by Django 3.1.1 on 2020-10-06 13:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0013_auto_20201006_1622'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mobile_phone',
            managers=[
                ('phones', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='mobile_phone',
            name='display',
            field=models.IntegerField(choices=[(5, '5.1 дюймов'), (12, '12.954 сантиметров')], default=5),
        ),
    ]
