# Generated by Django 3.1.1 on 2020-10-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0015_auto_20201006_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paintforcar',
            old_name='Наименование',
            new_name='nameofpaint',
        ),
    ]
