# Generated by Django 3.1.1 on 2020-10-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0016_auto_20201006_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name_of_product',
            new_name='category',
        ),
    ]
