# Generated by Django 3.1.1 on 2020-10-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0017_auto_20201007_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintforcar',
            options={'ordering': ['-pub_time'], 'verbose_name': 'Краску', 'verbose_name_plural': 'Краски'},
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'ordering': ['-pub_time'], 'verbose_name': 'Историю', 'verbose_name_plural': 'Истории'},
        ),
    ]
