# Generated by Django 3.1.1 on 2020-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(blank=True, max_length=300)),
                ('prod_type', models.CharField(blank=True, max_length=300)),
                ('prod_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('prod_proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('prod_fats', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('prod_carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-prod_name'],
            },
        ),
    ]
