# Generated by Django 3.1.1 on 2020-10-17 09:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0002_auto_20201016_2027'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodproduct',
            managers=[
                ('food', django.db.models.manager.Manager()),
            ],
        ),
    ]
