# Generated by Django 3.1.1 on 2020-10-21 10:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0003_auto_20201017_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(null=True, verbose_name='Понедельник')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
            managers=[
                ('day', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='testdateclass',
            constraint=models.CheckConstraint(check=models.Q(test_date__iexact='monday'), name='day_of_the_week_fits'),
        ),
    ]
