# Generated by Django 3.1.1 on 2020-10-21 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_calculator', '0005_auto_20201021_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('monday', models.DateField(null=True, verbose_name='Понедельник')),
                ('tuesday', models.DateField(null=True, verbose_name='Вторник')),
                ('wednesday', models.DateField(null=True, verbose_name='Среда')),
                ('thursday', models.DateField(null=True, verbose_name='Четверг')),
                ('friday', models.DateField(null=True, verbose_name='Пятница')),
                ('saturday', models.DateField(null=True, verbose_name='Суббота')),
                ('sunday', models.DateField(null=True, verbose_name='Воскресенье')),
            ],
            options={
                'verbose_name': 'Меню продуктов на неделю',
                'verbose_name_plural': 'Меню продуктов на неделю',
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='testdateclass',
            name='day_of_the_week_fits',
        ),
        migrations.AddConstraint(
            model_name='testdateclass',
            constraint=models.CheckConstraint(check=models.Q(test_date__iso_week_day=1), name='test_day_of_the_week_fits'),
        ),
        migrations.AddField(
            model_name='productmenu',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(('monday__iso_week_day', 1), ('tuesday__iso_week_day', 2), ('wednesday__iso_week_day', 3), ('thursday__iso_week_day', 4), ('friday__iso_week_day', 5), ('saturday__iso_week_day', 6), ('sunday__iso_week_day', 7), _connector='OR'), name='day_of_the_week_fits'),
        ),
    ]
