# Generated by Django 3.1.1 on 2020-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0006_auto_20201021_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmenu',
            name='friday',
            field=models.DateField(blank=True, null=True, verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='monday',
            field=models.DateField(blank=True, null=True, verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='saturday',
            field=models.DateField(blank=True, null=True, verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='sunday',
            field=models.DateField(blank=True, null=True, verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='thursday',
            field=models.DateField(blank=True, null=True, verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='tuesday',
            field=models.DateField(blank=True, null=True, verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='wednesday',
            field=models.DateField(blank=True, null=True, verbose_name='Среда'),
        ),
    ]
