# Generated by Django 3.1.1 on 2020-10-21 11:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0007_auto_20201021_1418'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productmenu',
            managers=[
                ('product_menu', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='productmenu',
            name='day_of_the_week_fits',
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('monday__isnull', False), ('monday__iso_week_day', 1)), models.Q(('tuesday__isnull', False), ('tuesday__iso_week_day', 2)), models.Q(('wednesday__isnull', False), ('wednesday__iso_week_day', 3)), models.Q(('thursday__isnull', False), ('thursday__iso_week_day', 4)), models.Q(('friday__isnull', False), ('friday__iso_week_day', 5)), models.Q(('saturday__isnull', False), ('saturday__iso_week_day', 6)), models.Q(('sunday__isnull', False), ('sunday__iso_week_day', 7)), _connector='OR'), name='day_of_the_week_fits'),
        ),
    ]
