# Generated by Django 3.1.1 on 2020-10-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0008_auto_20201021_1444'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmenu',
            name='day_of_the_week_fits',
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(('monday__isnull', False), ('monday__iso_week_day', 1)), name='check_monday'),
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(('monday__isnull', False), ('tuesday__iso_week_day', 2)), name='check_tuesday'),
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(('wednesday__isnull', False), ('wednesday__iso_week_day', 3)), name='check_wednesday'),
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(('thursday__isnull', False), ('thursday__iso_week_day', 4)), name='check_thursday'),
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(('friday__isnull', False), ('friday__iso_week_day', 5)), name='check_friday'),
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(('saturday__isnull', False), ('saturday__iso_week_day', 6)), name='check_saturday'),
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(('sunday__isnull', False), ('sunday__iso_week_day', 7)), name='check_sunday'),
        ),
    ]
