# Generated by Django 3.1.1 on 2020-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0009_auto_20201021_1453'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmenu',
            name='check_monday',
        ),
        migrations.AddConstraint(
            model_name='productmenu',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('monday__isnull', False), ('monday__iso_week_day', 1)), ('monday__isnull', True), _connector='OR'), name='check_monday'),
        ),
    ]
