# Generated by Django 3.1.1 on 2020-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0011_auto_20201021_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDateClass',
        ),
        migrations.AddField(
            model_name='productmenu',
            name='list_of_selected_products',
            field=models.ManyToManyField(to='food_calculator.FoodProduct'),
        ),
    ]
