# Generated by Django 3.1.1 on 2020-10-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0012_auto_20201021_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmenu',
            name='list_of_selected_products',
            field=models.ManyToManyField(default=None, to='food_calculator.FoodProduct', verbose_name='Лист продуктов'),
        ),
    ]
