# Generated by Django 3.1.1 on 2020-10-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0016_auto_20201021_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmenu',
            name='list_of_selected_products',
        ),
        migrations.AddField(
            model_name='productmenu',
            name='list_of_selected_products_friday',
            field=models.ManyToManyField(blank=True, default=None, related_name='_productmenu_list_of_selected_products_friday_+', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на пятницу'),
        ),
        migrations.AddField(
            model_name='productmenu',
            name='list_of_selected_products_monday',
            field=models.ManyToManyField(blank=True, default=None, related_name='_productmenu_list_of_selected_products_monday_+', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на понедельник'),
        ),
        migrations.AddField(
            model_name='productmenu',
            name='list_of_selected_products_saturday',
            field=models.ManyToManyField(blank=True, default=None, related_name='_productmenu_list_of_selected_products_saturday_+', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на субботу'),
        ),
        migrations.AddField(
            model_name='productmenu',
            name='list_of_selected_products_sunday',
            field=models.ManyToManyField(blank=True, default=None, related_name='_productmenu_list_of_selected_products_sunday_+', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на воскресенье'),
        ),
        migrations.AddField(
            model_name='productmenu',
            name='list_of_selected_products_thursday',
            field=models.ManyToManyField(blank=True, default=None, related_name='_productmenu_list_of_selected_products_thursday_+', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на четверг'),
        ),
        migrations.AddField(
            model_name='productmenu',
            name='list_of_selected_products_tuesday',
            field=models.ManyToManyField(blank=True, default=None, related_name='_productmenu_list_of_selected_products_tuesday_+', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на вторник'),
        ),
        migrations.AddField(
            model_name='productmenu',
            name='list_of_selected_products_wednesday',
            field=models.ManyToManyField(blank=True, default=None, related_name='_productmenu_list_of_selected_products_wednesday_+', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на среду'),
        ),
    ]
