# Generated by Django 3.1.1 on 2020-10-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calculator', '0019_auto_20201023_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmenu',
            name='list_of_selected_products_friday',
            field=models.ManyToManyField(blank=True, default=None, related_name='friday', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на пятницу'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='list_of_selected_products_monday',
            field=models.ManyToManyField(blank=True, default=None, related_name='monday', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на понедельник'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='list_of_selected_products_saturday',
            field=models.ManyToManyField(blank=True, default=None, related_name='saturday', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на субботу'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='list_of_selected_products_sunday',
            field=models.ManyToManyField(blank=True, default=None, related_name='sunday', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на воскресенье'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='list_of_selected_products_thursday',
            field=models.ManyToManyField(blank=True, default=None, related_name='thursday', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на четверг'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='list_of_selected_products_tuesday',
            field=models.ManyToManyField(blank=True, default=None, related_name='tuesday', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на вторник'),
        ),
        migrations.AlterField(
            model_name='productmenu',
            name='list_of_selected_products_wednesday',
            field=models.ManyToManyField(blank=True, default=None, related_name='wednesday', to='food_calculator.FoodProduct', verbose_name='Лист продуктов на среду'),
        ),
    ]
